#!/bin/bash

#
# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

DEFAULT_ETCD_IMAGE_NAME="bitnami/etcd"
DEFAULT_ETCD_IMAGE_TAG="3.5.4"

DEFAULT_APISIX_IMAGE_NAME="apache/apisix"
DEFAULT_APISIX_IMAGE_TAG="3.1.0-debian"

DEFAULT_ETCD_LISTEN_HOST=127.0.0.1
DEFAULT_ETCD_LISTEN_PORT=2379

DEFAULT_APISIX_PORT=9180

DEFAULT_ETCD_NAME="etcd"
DEFAULT_APP_NAME="apisix-quickstart"

usage() {
  echo "Runs a Docker based Apache APISIX."
  echo
  echo "See the document for more information:"
  echo "  https://docs.api7.ai/apisix/getting-started"
  exit 0
}

echo_fail() {
  printf "\e[31m✘ \033\e[0m$@\n"
}

echo_pass() {
  printf "\e[32m✔ \033\e[0m$@\n"
}

ensure_docker() {
  {
    docker ps -q > /dev/null 2>&1
  } || {
    return 1
  }
}

ensure_curl() {
  {
    curl -h > /dev/null 2>&1
  } || {
    return 1
  }
}

install_apisix() {
  echo Starting the container $DEFAULT_ETCD_NAME
  docker run -d \
    --name ${DEFAULT_ETCD_NAME} \
    --network="host" \
    -e ALLOW_NONE_AUTHENTICATION=yes \
    -e ETCD_ADVERTISE_CLIENT_URLS=http://${DEFAULT_ETCD_LISTEN_HOST}:${DEFAULT_ETCD_LISTEN_PORT} \
    ${DEFAULT_ETCD_IMAGE_NAME}:${DEFAULT_ETCD_IMAGE_TAG} && echo_pass "etcd is listening on ${DEFAULT_ETCD_LISTEN_HOST}:${DEFAULT_ETCD_LISTEN_PORT}" || {
          echo_fail "start etcd failed"
    return 1
  }
  
  echo ""
  
  echo Starting the container $DEFAULT_APP_NAME
  docker run -d \
    --name ${DEFAULT_APP_NAME} \
    --network="host" \
    ${DEFAULT_APISIX_IMAGE_NAME}:${DEFAULT_APISIX_IMAGE_TAG} && validate_apisix && sleep 2

  docker exec ${DEFAULT_APP_NAME} /bin/bash -c "echo '
deployment:
  role: traditional
  role_traditional:
    config_provider: etcd
  admin:
    admin_key:
  ' > /usr/local/apisix/conf/config.yaml"
  docker exec ${DEFAULT_APP_NAME} apisix reload >> /dev/null 2>&1

  echo ""
}

destroy_apisix() {
  echo Destroying previous $DEFAULT_APP_NAME containers
  docker rm -f $DEFAULT_APP_NAME >> /dev/null 2>&1
  docker rm -f $DEFAULT_ETCD_NAME >> /dev/null 2>&1
}

validate_apisix() {
  local rv=0
  retry 30 curl "http://localhost:${DEFAULT_APISIX_PORT}/apisix/admin/services" >> /dev/null 2>&1 && echo_pass "APISIX is up" || rv=$?
}

main() {
  ensure_docker || { 
    echo_fail "Docker is not available, please install it first"; exit 1 
  }

  ensure_curl || { 
    echo_fail "curl is not available, please install it first"; exit 1 
  }

  destroy_apisix

  install_apisix || {
    echo_fail "Start APISIX failed."; exit 1 
  }

    
  echo_pass "APISIX is ready!"
}

main "$@"
