name: Auto Preview

on:
  pull_request:
    branches:
      - main
      - release/**
    types: [opened, synchronize, reopened, labeled, closed]

concurrency:
  group: staging-${{ github.ref }}
  cancel-in-progress: true

jobs:
  deploy:
    if: github.event.action != 'closed'
    timeout-minutes: 20
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: Azure/docker-login@v1
        with:
          login-server: ${{ secrets.REGISTRY_NAME }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - id: set-deploy-comment-body
        name: Set deploy comment body
        run: |
          DATE=$(date)
          echo "**The auto preview on your projects!**." >> deploy.txt
          echo "| Name | Status | Preview | Updated|" >> deploy.txt
          echo "| :--- | :----- | :------ | :------ |" >> deploy.txt
          echo "| **api7 docs** | Deploying | | $DATE |" >> deploy.txt
          BODY=$(cat deploy.txt)
          BODY="${BODY//'%'/'%25'}"
          BODY="${BODY//$'\n'/'%0A'}"
          BODY="${BODY//$'\r'/'%0D'}"
          echo "::set-output name=body::$BODY"

      - name: Find comment
        uses: peter-evans/find-comment@v2
        id: fc
        with:
          issue-number: ${{ github.event.pull_request.number }}
          body-includes: "The auto preview on your projects!"

      - name: Create comment
        if: steps.fc.outputs.comment-id == ''
        uses: peter-evans/create-or-update-comment@v2
        with:
          issue-number: ${{ github.event.pull_request.number }}
          body: ${{ steps.set-deploy-comment-body.outputs.body }}

      - name: Build API7 Docs Images
        env:
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
        run: |
          docker build -t api7/api7-docs:dev .

      - name: Push api7 docs Images
        env:
          REGISTRY: ${{ secrets.REGISTRY_NAME }}
        run: |
          docker tag api7/api7-docs:dev $REGISTRY/api7-docs:${{ github.event.pull_request.number }}
          docker push $REGISTRY/api7-docs:${{ github.event.pull_request.number }}

      - uses: azure/login@v1
        with:
          environment: AzureCloud
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Install API7 Docs
        run: |
          az account set --subscription ffb9d49d-93e7-4f61-bf47-1e9b5f9e4cc0
          az aks get-credentials --resource-group API7-Web-Preview_group --name API7-Web-Preview
          export ID=${{ github.event.pull_request.number }}
          sh ./preview/install.sh
          kubectl rollout restart deployment/api7-docs-${{ github.event.pull_request.number }} -n api7-docs

      - id: set-preview-comment-body
        name: Set preview comment body
        run: |
          DATE=$(date)
          echo "**The auto preview on your projects!**." >> preview.txt
          echo "| Name | Status | Preview | Updated|" >> preview.txt
          echo "| :--- | :----- | :------ | :------ |" >> preview.txt
          echo "| **api7-docs** | ✅  Ready | [Visit Preview](http://api7-docs-${{ github.event.pull_request.number }}.preview.api7.ai) | $DATE |" >> preview.txt
          BODY=$(cat preview.txt)
          BODY="${BODY//'%'/'%25'}"
          BODY="${BODY//$'\n'/'%0A'}"
          BODY="${BODY//$'\r'/'%0D'}"
          echo "::set-output name=body::$BODY"

      - name: Find comment
        uses: peter-evans/find-comment@v2
        id: fc2
        with:
          issue-number: ${{ github.event.pull_request.number }}
          body-includes: "The auto preview on your projects!"

      - name: Update comment
        if: steps.fc2.outputs.comment-id != ''
        uses: peter-evans/create-or-update-comment@v2
        with:
          comment-id: ${{ steps.fc2.outputs.comment-id }}
          edit-mode: replace
          body: ${{ steps.set-preview-comment-body.outputs.body }}

  clean:
    if: github.event.action == 'closed'
    timeout-minutes: 15
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: Azure/docker-login@v1
        with:
          login-server: ${{ secrets.REGISTRY_NAME }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - uses: azure/login@v1
        with:
          environment: AzureCloud
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Uninstall API7 Docs
        run: |
          az account set --subscription ffb9d49d-93e7-4f61-bf47-1e9b5f9e4cc0
          az aks get-credentials --resource-group API7-Web-Preview_group --name API7-Web-Preview
          export ID=${{ github.event.pull_request.number }}
          sh ./preview/uninstall.sh
